"""Shared executable fixtures for headless and native Sublime verification."""

# Each case uses the actual saved settings. Rule changes exercise extensibility.
CASES = (
    dict(name="external links", source='<a href="https://example.com">External</a><a href="/course" target="_blank">Internal</a>', expected='<a href="https://example.com" target="_blank" rel="noopener noreferrer">External</a><a href="/course">Internal</a>'),
    dict(name="external rel tokens preserved", source='<a href="HTTP://EXAMPLE.COM" rel="nofollow ugc">Link</a>', expected='<a href="HTTP://EXAMPLE.COM" target="_blank" rel="nofollow ugc noopener noreferrer">Link</a>'),
    dict(name="quoted greater than", source='<a title="x > y" href="https://example.com">Link</a>', expected='<a title="x > y" href="https://example.com" target="_blank" rel="noopener noreferrer">Link</a>'),
    dict(name="nested paragraphs", source='<div class="card"><p><p>First</p><p>Second</p></p></div>', expected='<div class="card"><p>First</p><p>Second</p></div>'),
    dict(name="ordinary paragraph", source='<p>Intro <strong>important</strong> text.</p>', expected='<p>Intro <strong>important</strong> text.</p>'),
    dict(name="nested paragraph text preserved", source='<p>Intro<p>Child</p></p>', expected='<p>Intro<p>Child</p></p>'),
    dict(name="structural wrappers", source='<section><article><div><p>Content</p></div></article></section>', expected='<p>Content</p>'),
    dict(name="remove wins over unwrap", source='<section class="delete"><p>Remove</p></section><p>Keep</p>', expected='<p>Keep</p>', extra_rules=[dict(id='custom-remove', action='remove', selector='section.delete')]),
    dict(name="readspeaker removal", source='<p>Before <a href="https://app.readspeaker.com/listen">Listen</a> after.</p><img src="https://app.readspeaker.com/icon.png">', expected='<p>Before  after.</p>'),
    dict(name="readspeaker empty paragraph removed", source='<p><a href="https://app.readspeaker.com/listen">Listen</a></p>', expected=''),
    dict(name="editor artifacts", source='<p dir="ltr" style="text-align: left;" id="yui_123">Text</p>', expected='<p>Text</p>'),
    dict(name="TinyMCE attributes", source='<p data-mce-style="left" data-purpose="layout">Text</p><img DATA-MCE-SRC=\'draft.jpg\' src="real.jpg" alt="Image" data-mce-selected="1">', expected='<p data-purpose="layout">Text</p><img src="real.jpg" alt="Image">'),
    dict(name="attribute removal configurable", source='<p data-mce-style="left">Text</p>', expected='<p data-mce-style="left">Text</p>', disable=['editor-attributes']),
    dict(name="attribute wildcards exact scope", source='<p data-old="x" data-test-one="x" data-test="keep" data-other="keep">data-old="text"</p>', expected='<p data-test="keep" data-other="keep">data-old="text"</p>', extra_rules=[dict(id='custom-attributes',action='attributes',selector='p',remove=['DATA-OLD','data-test-*'])]),
    dict(name="class token cleanup", source='<p class="notBodycopyindentedExtra Bodycopyindented rspkr_dr_added">Text</p>', expected='<p class="notBodycopyindentedExtra">Text</p>'),
    dict(name="image class replacement", source='<img class="atto_image_button_text-bottom other" src="x"><p class="atto_image_button_text-bottom">Keep</p>', expected='<img class="w-100 other" src="x"><p class="atto_image_button_text-bottom">Keep</p>'),
    dict(name="style keeps color", source='<p style="font-size: 1rem; color: red;">Text</p>', expected='<p style="color: red;">Text</p>'),
    dict(name="single quoted style", source="<p style='font-size: 1rem; color: red;'>Text</p>", expected='<p style="color: red;">Text</p>'),
    dict(name="CSS quoted delimiters", source='<p style="font-size: 1rem; background: url(\'data:x;a:b\'); --label: \'a;b:c\'; color: blue;">Text</p>', expected='<p style="background: url(\'data:x;a:b\'); --label: \'a;b:c\'; color: blue;">Text</p>'),
    dict(name="CSS comments retained", source='<p style="font-size: 1rem; /* keep ; : */ color: red;">Text</p>', expected='<p style="/* keep ; : */ color: red;">Text</p>'),
    dict(name="image timestamp query", source='<img src="x.jpg?time=1712345678901&token=a%2Bb#frag"><img src="x.jpg?time1712345678">', expected='<img src="x.jpg?token=a%2Bb#frag"><img src="x.jpg">'),
    dict(name="unrelated timestamps retained", source='<p>runtime12345678 time12345678</p><a href="/file?time12345678&x=1">File</a>', expected='<p>runtime12345678 time12345678</p><a href="/file?time12345678&x=1">File</a>'),
    dict(name="local fragment scoped", source='<a href="http://127.0.0.1/page#target">Jump</a><p>http://127.0.0.1/page#target</p>', expected='<a href="#target">Jump</a><p>http://127.0.0.1/page#target</p>'),
    dict(name="list markers with attributes", source='<ul><li>• One</li><li class="x"># Two</li><li>10. Ten</li><li>-5 degrees</li><li>0. Zero</li></ul>', expected='<ul><li>One</li><li class="x">Two</li><li>Ten</li><li>-5 degrees</li><li>Zero</li></ul>'),
    dict(name="list markers inline", source='<ul><li><strong>• One</strong> later</li></ul>', expected='<ul><li><strong>One</strong> later</li></ul>'),
    dict(name="list markers after indentation", source='<ul><li>\n  <strong>• One</strong> later</li></ul>', expected='<ul><li>\n  <strong>One</strong> later</li></ul>'),
    dict(name="single list paragraph", source='<ul><li><p>Only</p></li></ul>', expected='<ul><li>Only</li></ul>'),
    dict(name="multiple list paragraphs", source='<ul><li><p>First</p><p>Second</p></li></ul>', expected='<ul><li><p>First</p><p>Second</p></li></ul>'),
    dict(name="styled list paragraph", source='<ul><li><p class="notice">Only</p></li></ul>', expected='<ul><li><p class="notice">Only</p></li></ul>'),
    dict(name="heading emphasis", source='<h2><strong>Strong</strong> and <em>emphasis</em></h2>', expected='<h2>Strong and emphasis</h2>'),
    dict(name="heading icons and attributes", source='<h3><i class="icon"></i><strong aria-hidden="true">!</strong><em class="label">Notice</em></h3>', expected='<h3><i class="icon">&nbsp;</i><strong aria-hidden="true">!</strong><em class="label">Notice</em></h3>'),
    dict(name="named anchor preserved", source='<a name="topic" href="/course">Course</a><a href="#topic">Jump</a>', expected='<a name="topic" href="/course">Course</a><a href="#topic">Jump</a>'),
    dict(name="empty fragment target preserved", source='<p id="target"></p><a href="#target">Jump</a>', expected='<p id="target">&nbsp;</p><a href="#target">Jump</a>'),
    dict(name="empty protected elements", source='<div></div><span class="icon"></span><i aria-hidden="true">&#160;</i><img src="x">', expected='<div>&nbsp;</div><span class="icon">&nbsp;</span><i aria-hidden="true">&nbsp;</i><img src="x">'),
    dict(name="empty nested lists removed", source='<ul><li><strong></strong></li></ul>', expected=''),
    dict(name="newly empty div padded", source='<div class="spacer"><p></p></div>', expected='<div class="spacer">&nbsp;</div>'),
    dict(name="newly empty bare div padded", source='<div><p></p></div>', expected='<div>&nbsp;</div>'),
    dict(name="editor only placeholder cleaned consistently", source='<strong data-mce-style="x">&nbsp;</strong>', expected=''),
    dict(name="editor-only div consistently unwrapped", source='<div data-mce-style="x"><p>Keep</p></div>', expected='<p>Keep</p>'),
    dict(name="ordinary NBSP and placeholders", source='<strong class="icon">&nbsp;</strong><p>&nbsp;</p><p>Word&nbsp;word</p>', expected='<strong class="icon">&nbsp;</strong><p>Word word</p>'),
    dict(name="attributed div preserved", source='<div data-purpose="layout"><p>Text</p></div>', expected='<div data-purpose="layout"><p>Text</p></div>'),
    dict(name="BR following character kept", source='<p>A<br>x</p>', expected='<p>A<br>x</p>'),
    dict(name="BR variants preserved", source='<p>A<br>B<br/>C<br />D<BR>E</p>', expected='<p>A<br>B<br>C<br>D<br>E</p>'),
    dict(name="paragraph only BR", source='<p><br></p>', expected=''),
    dict(name="styled paragraph only BR", source='<p style="text-align: left;" data-mce-style="text-align: left;"> <br> </p>', expected=''),
    dict(name="paragraph multiple BR", source='<p><br><br/></p>', expected=''),
    dict(name="paragraph only image", source='<p><img class="img-fluid" data-mce-src="x.jpg" src="x.jpg"></p>', expected='<img class="img-fluid" src="x.jpg">'),
    dict(name="styled paragraph only image", source='<p style="text-align: center;"><img src="x.jpg"></p>', expected='<img src="x.jpg">'),
    dict(name="mixed image paragraph retained", source='<p>Caption <img src="x.jpg"></p>', expected='<p>Caption <img src="x.jpg"></p>'),
    dict(name="pre image paragraph retained", source='<pre><p><img src="x.jpg"></p></pre>', expected='<pre><p><img src="x.jpg"></p></pre>'),
    dict(name="trailing paragraph BR only", source='<p>Text<br><br></p>', expected='<p>Text</p>'),
    dict(name="bogus breaks and Harper", source='<p>A<br data-mce-bogus="1">B</p><harper-render-box><p>Overlay</p></harper-render-box>', expected='<p>AB</p>'),
    dict(name="pre whitespace", source='<pre>line one\n    line two&nbsp;[OPTIONAL]</pre>', expected='<pre>line one\n    line two&nbsp;[OPTIONAL]</pre>'),
    dict(name="raw script and code", source='<script>const s = "<br> time12345678";</script><code>time12345678</code><textarea>Line\n  next</textarea>', expected='<script>const s = "<br> time12345678";</script><code>time12345678</code><textarea>Line\n  next</textarea>'),
    dict(name="deep optional marker scoped", mode='deep', source='<p>Before [OPTIONAL] after</p><code> [OPTIONAL] </code>', expected='<p>Before after</p><code> [OPTIONAL] </code>'),
    dict(name="canvas policy and numbers", mode='canvas', source='<!-- comment --><p>Invoice 9864 <a href="https://example.com/9864">File</a><br></p>', expected='<p>Invoice 9864 <a href="https://example.com/9864" rel="noopener noreferrer">File</a></p>'),
    dict(name="table single cell", mode='table', source='<table><tbody><tr><td>Cell</td></tr></tbody></table>', expected='Cell'),
    dict(name="table plain header h3", mode='table', source='<table><thead><tr><th>Heading</th></tr></thead><tbody><tr><td><p>Cell <em>HTML</em></p></td></tr></tbody></table>', expected='<h3>Heading</h3>\n<p>Cell <em>HTML</em></p>'),
    dict(name="table formatted header keeps HTML", mode='table', source='<table><tr><th><strong>Header</strong></th><td><img src="x">Text</td></tr></table>', expected='<strong>Header</strong> <img src="x">Text'),
    dict(name="table cells footer and column markup", mode='table', source='<table><colgroup><col></colgroup><tbody><tr><td>One</td><td>Two</td></tr></tbody><tfoot><tr><td>Foot</td></tr></tfoot></table>', expected='One Two\nFoot'),
    dict(name="normal table preserved", source='<table><tr><th>Heading</th><td>Cell</td></tr></table>', expected='<table><tr><th>Heading</th><td>Cell</td></tr></table>'),
    dict(name="attribution helper", source='<a class="source-btn" data-toggle="collapse" href="#show-123">▼ Show attribution</a>', expected='<a class="source-btn text-muted" data-toggle="collapse" href="#show-123">▽ Show attribution</a>'),
    dict(name="structural comments own lines", source='<div class="col">A</div><!-- End of Grid item --> <div class="col">B</div>', expected='<div class="col">A</div>\n<!-- End of Grid item -->\n<div class="col">B</div>'),
    dict(name="structural start comment own line", source='<div class="row"><!-- Start of Grid item --><div class="col">A</div><!-- End of Grid item --></div>', expected='<div class="row">\n<!-- Start of Grid item -->\n<div class="col">A</div>\n<!-- End of Grid item -->\n</div>'),
    dict(name="code comment boundaries retained", source='<pre>A<!-- End of example -->B</pre>', expected='<pre>A<!-- End of example -->B</pre>'),
    dict(name="comments policy", source='<!-- [if IE]>legacy<![endif]--><!-- keep --><p>Text</p>', expected='<!-- keep --><p>Text</p>'),
    dict(name="custom text regex and backreference", source='<p>Code A123</p><code>Code A123</code>', expected='<p>Code [123]</p><code>Code A123</code>', extra_rules=[dict(id='custom-text',action='text',selector='p',pattern=r'A(\d+)',replacement=r'[\1]')]),
    dict(name="custom protection selector", source='<p class="spacer"></p><strong></strong>', expected='<p class="spacer">&nbsp;</p>', protect=['p.spacer']),
    dict(name="audio body order", source='<!doctype html><html><body><p>Before</p><audio src="a"></audio><p>Middle</p><audio src="b"></audio></body></html>', expected='<!doctype html><html><body><audio src="a"></audio><audio src="b"></audio><div class="clearfix container-fluid">&nbsp;</div><p>Before</p><p>Middle</p></body></html>', enable=['audio-hoisting']),
)
