"""Executable CleanHTML cases shared by the project test runner."""

FUNCTION_CASES = (
    {
        "name": "External links gain safe attributes while internal links remain local",
        "function": "normalize_external_links",
        "input": '<p><a href="https://example.com">External</a> and <a href="/internal">Internal</a></p>',
        "expected": '<p><a href="https://example.com" rel="noopener noreferrer" target="_blank">External</a> and <a href="/internal">Internal</a></p>',
    },
    {
        "name": "External link matching is case insensitive",
        "function": "normalize_external_links",
        "input": '<a href="HTTP://EXAMPLE.COM" rel="old" target="frame">Example</a>',
        "expected": '<a href="HTTP://EXAMPLE.COM" rel="noopener noreferrer" target="_blank">Example</a>',
    },
    {
        "name": "Relative links lose unsafe inherited target attributes",
        "function": "normalize_external_links",
        "input": '<a href="/course" rel="external" target="_blank">Course</a>',
        "expected": '<a href="/course">Course</a>',
    },
    {
        "name": "Nested paragraph wrappers are repaired",
        "function": "repair_nested_paragraph_wrappers",
        "input": '<div class="card-body gb-bs-content"><p><p>First paragraph.</p><p>Second paragraph.</p></p></div>',
        "expected": '<div class="card-body gb-bs-content"><p>First paragraph.</p><p>Second paragraph.</p></div>',
    },
    {
        "name": "Ordinary paragraph content is preserved",
        "function": "repair_nested_paragraph_wrappers",
        "input": "<p>Intro <strong>important</strong> text.</p>",
        "expected": "<p>Intro <strong>important</strong> text.</p>",
    },
)

STRUCTURE_CASES = (
    {
        "name": "Empty div span and i elements gain placeholders even in MP mode",
        "mode": "mp",
        "input": '<div></div><span> </span><i class="icon"></i><span>Keep text</span><p></p>',
        "config": {"protect_empty_selectors": ["div", "span", "i"], "unwrap_selectors": ["div:not([class]):not([id]):not([style])"]},
        "expected": '<div>&nbsp;</div><span> &nbsp;</span><i class="icon">&nbsp;</i>Keep text',
        "removed": 2,
    },
    {
        "name": "TinyMCE attributes are removed while real image and data attributes survive",
        "mode": "normal",
        "input": '<p data-mce-style="text-align: left;" style="text-align: right;" data-purpose="layout">Text</p><img DATA-MCE-SRC=\'draft.jpg\' src="real.jpg" alt="Image" data-mce-selected="1">',
        "config": {},
        "expected": '<p style="text-align: right;" data-purpose="layout">Text</p><img src="real.jpg" alt="Image">',
        "removed": 0,
    },
    {
        "name": "Attribute matching supports exact names and star wildcards only",
        "mode": "canvas",
        "input": '<p data-old="x" data-test-one="y" data-test="keep" data-a="keep" data-other="keep">data-old="text"</p>',
        "config": {"remove_attributes": ["DATA-OLD", "data-test-*", "data-?", None, ""]},
        "expected": '<p data-test="keep" data-a="keep" data-other="keep">data-old="text"</p>',
        "removed": 0,
    },
    {
        "name": "Empty attribute removal list disables TinyMCE attribute removal",
        "mode": "normal",
        "input": '<p data-mce-style="color: red;">Text</p>',
        "config": {"remove_attributes": []},
        "expected": '<p data-mce-style="color: red;">Text</p>',
        "removed": 0,
    },
    {
        "name": "Attributed empty placeholders survive and ordinary spaces are normalised",
        "mode": "normal",
        "input": '<span class="icon" aria-hidden="true">&nbsp;</span><strong class="icon">&#160;</strong><p>&nbsp;</p><p>Word&nbsp;word</p>',
        "config": {},
        "expected": '<span class="icon" aria-hidden="true">&nbsp;</span><strong class="icon">&nbsp;</strong><p>Word word</p>',
        "removed": 1,
    },
    {
        "name": "Selected empty tags gain placeholders and bypass unwrap and empty removal",
        "mode": "normal",
        "input": '<div class="spacer"></div><h2><strong class="icon"></strong>Heading</h2><p></p><img class="spacer" src="x"><span class="spacer">Content</span>',
        "config": {"protect_empty_selectors": [".spacer", ".icon", "[", None], "unwrap_selectors": ["div.spacer"]},
        "expected": '<div class="spacer">&nbsp;</div><h2><strong class="icon">&nbsp;</strong>Heading</h2><img class="spacer" src="x"><span class="spacer">Content</span>',
        "removed": 1,
    },
    {
        "name": "Placeholder preservation can be disabled",
        "mode": "normal",
        "input": '<strong class="icon">&nbsp;</strong><span class="icon">&nbsp;</span>',
        "config": {"preserve_nbsp_placeholders": False},
        "expected": '<span class="icon"> </span>',
        "removed": 1,
    },
    {
        "name": "Explicit selector removal still removes protected elements",
        "mode": "normal",
        "input": '<div class="delete">&nbsp;</div>',
        "config": {"protect_empty_selectors": [".delete"], "remove_selectors": [".delete"]},
        "expected": '',
        "removed": 1,
    },
    {
        "name": "Configured structural wrappers are unwrapped",
        "mode": "normal",
        "input": "<section><article><p>Content</p></article></section>",
        "config": {"unwrap_selectors": ["section", "article"], "remove_selectors": []},
        "expected": "<p>Content</p>",
        "removed": 2,
    },
    {
        "name": "Configured ReadSpeaker artifacts are removed",
        "mode": "normal",
        "input": '<p>Before <a href="https://app.readspeaker.com/listen">Listen</a> after.</p><img src="https://app.readspeaker.com/icon.png"/>',
        "config": {
            "unwrap_selectors": [],
            "remove_selectors": [
                'a[href*="readspeaker.com"]',
                'img[src*="readspeaker.com"]',
            ],
        },
        "expected": "<p>Before  after.</p>",
        "removed": 2,
    },
    {
        "name": "Heading emphasis wrappers are simplified",
        "mode": "normal",
        "input": "<h2><strong>Strong</strong> and <em>emphasised</em></h2>",
        "config": {"unwrap_selectors": [], "remove_selectors": []},
        "expected": "<h2>Strong and emphasised</h2>",
        "removed": 2,
    },
    {
        "name": "Meaningful heading icons are preserved",
        "mode": "normal",
        "input": '<h3><i class="fa fa-info"></i> Information</h3>',
        "config": {"unwrap_selectors": [], "remove_selectors": []},
        "expected": '<h3><i class="fa fa-info"></i> Information</h3>',
        "removed": 0,
    },
    {
        "name": "Aria-hidden heading wrappers are preserved",
        "mode": "normal",
        "input": '<h3><strong aria-hidden="true">!</strong> Warning</h3>',
        "config": {"unwrap_selectors": [], "remove_selectors": []},
        "expected": '<h3><strong aria-hidden="true">!</strong> Warning</h3>',
        "removed": 0,
    },
    {
        "name": "Empty known tags are removed",
        "mode": "normal",
        "input": "<div><p></p><strong> </strong><p>Keep me</p></div>",
        "config": {"unwrap_selectors": [], "remove_selectors": []},
        "expected": "<div><p>Keep me</p></div>",
        "removed": 2,
    },
    {
        "name": "Table mode unwraps table structure but keeps cell content",
        "mode": "table",
        "input": "<table><tbody><tr><td>Cell</td></tr></tbody></table>",
        "config": {"unwrap_selectors": [], "remove_selectors": []},
        "expected": "Cell",
        "removed": 4,
    },
    {
        "name": "Normal mode preserves table structure",
        "mode": "normal",
        "input": "<table><tbody><tr><td>Cell</td></tr></tbody></table>",
        "config": {"unwrap_selectors": [], "remove_selectors": []},
        "expected": "<table><tbody><tr><td>Cell</td></tr></tbody></table>",
        "removed": 0,
    },
    {
        "name": "Bare div wrappers can be unwrapped by the guarded selector",
        "mode": "normal",
        "input": "<div><p>Content</p></div>",
        "config": {
            "unwrap_selectors": ["div:not([class]):not([id]):not([style])"],
            "remove_selectors": [],
        },
        "expected": "<p>Content</p>",
        "removed": 1,
    },
    {
        "name": "Attributed div wrappers survive the guarded selector",
        "mode": "normal",
        "input": '<div data-purpose="layout"><p>Content</p></div>',
        "config": {
            "unwrap_selectors": ["div:not([class]):not([id]):not([style])"],
            "remove_selectors": [],
        },
        "expected": '<div data-purpose="layout"><p>Content</p></div>',
        "removed": 0,
    },
)
